version: '3.8'

services:
  strapi-db:
    image: arunrascall/strapi-postgres:development
    container_name: strapi-db
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi-user
      POSTGRES_DB: strapi-db
    ports:
      - "5432:5432"
    volumes:
      - /opt:/var/lib/postgsql/data
  strapi:
    build: .
    container_name: strapi-server
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapi-db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi-db
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi-user
    ports:
      - "1337:1337"
    depends_on:
      - strapi-db
