name: SonarQube Scan

on:
  push:
    branches:
      - Dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust this according to your Python project

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Yarn
        run: npm install -g yarn  # Install Yarn globally

      - name: Install Yarn dependencies
        run: |
          yarn install  # Adjust this according to your React.js project

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=STS
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.language=py  # Language setting for Python
            -Dsonar.python.coverage.reportPaths=coverage.xml  # Path to Python coverage report
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info  # Path to JavaScript coverage report
            -Dsonar.exclusions=**/node_modules/**,**/*.js  # Exclusions as needed

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
